services:
  # Backend service
  products-service:
    container_name: products-service
    build:
      context: ./products-service
    ports:
      - "8080:8080"

  # Frontend app
  pizza-app:
    container_name: pizza-app
    build:
      context: ./pizza-app
    ports:
      - "5173:5173"