services:
  # Backend service
  products-service:
    container_name: products-service
    build:
      context: ./products-service
    ports:
      - "8001:8001"
    network_mode: host

  db:
    image: postgres:14.1
    container_name: products-postgres
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=products_dev
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
    networks:
      - app_network

  # Frontend app
  pizza-app:
    container_name: pizza-app
    build:
      context: ./pizza-app
    ports:
      - "5173:5173"

networks:
  app_network:
    driver: bridge